name = "Tortuosity"
uuid = "80bb5c7f-3561-4bbc-a7c3-5e29a4cab6cc"
authors = ["Amin Sadeghi <amin.sadeghi@live.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
